### ISSUE TITLE
Mod versions for Minecraft 1.19.4 and 1.19.2

### ISSUE THREAD

**Issue by BRAiNS4GAMES** [Anxietie/Ambient-Fireflies#2]
Hi anxietie,

thank you for making the best firefly mod ever!

It would be fantastic if you could provide versions for Minecraft 1.19.4 and 1.19.2.

Keep up the good work!

**Comment by Anxietie** [comment]
good idea
might look into making 1.19 versions when I have the time (along with some more immersive updates)

**Comment by BRAiNS4GAMES** [comment]
Please be so kind and take the time to do at least a port to 1.19.4.
No new features needed. I would be happy with it like it is now.

**Comment by Anxietie** [comment]
ive been really busy but expect a port in the next couple weeks
