### ISSUE TITLE
Frogs Should Eat Fireflies

### ISSUE THREAD

**Issue by MinecraftGuy926** [Anxietie/Ambient-Fireflies#3]
![AAuE7mAtWKJOQnLoZj-ZC4OWU2giaMjqPtaKONI5=s900-mo-c-c0xffffffff-rj-k-no-3152776535](https://github.com/Anxietie/Ambient-Fireflies/assets/156498626/fac43f53-03ad-46f5-818c-823e3ad10ffd)

**Comment by Anxietie** [comment]
lol thatll come in a later update when i have time

**Comment by Anxietie** [comment]
done
